kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-ceph1
  annotations:
    volume.beta.kubernetes.io/storage-class: opensds-ceph1
    fsType: "ext4"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
